version: '3'
services:
  refresh-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    ports:
      - 8002:8002
    env_file:
      - .env